[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "demo-uagent"
version = "0.1.0"
description = "A demonstration of a uAgent client for the science chat API."
dependencies = [
    "uagents==0.11.2",
    "aiohttp",
    "python-dotenv",
    "uagents-core"
]
