services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=igor.gulamov@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/letsencrypt

  uneditor:
    build:
      context: https://github.com/auditdbio/uneditor-ethcannes.git#:demo-uagent
      dockerfile: Dockerfile
    container_name: uneditor-agent
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uneditor.rule=Host(`uneditor.xyz`)"
      - "traefik.http.routers.uneditor.entrypoints=websecure"
      - "traefik.http.routers.uneditor.tls.certresolver=letsencrypt"
      - "traefik.http.services.uneditor.loadbalancer.server.port=8080"
      - "traefik.http.routers.uneditor.middlewares=redirect-to-https"

networks:
  proxy:
    name: traefik_proxy

volumes:
  traefik-public-certificates: 