services:
  science-agent-dev:
    build:
      context: ..
      dockerfile: agent/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./agent_cache:/app/agent/agent_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 